name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v4
        with:
          context: ./base
          file: ./base/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base
          cache-to: type=inline

      - name: Build and push rstudio-minimal image
        uses: docker/build-push-action@v4
        with:
          context: ./rstudio-minimal
          file: ./rstudio-minimal/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rstudio-minimal
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rstudio-minimal
          cache-to: type=inline

      - name: Build and push python image
        uses: docker/build-push-action@v4
        with:
          context: ./python
          file: ./python/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:python
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rstudio-minimal
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:python
          cache-to: type=inline

      - name: Build and push jupyterlab image
        uses: docker/build-push-action@v4
        with:
          context: ./jupyterlab
          file: ./jupyterlab/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:python
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline 